//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace institute_Console_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentDataTable
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public Nullable<int> age { get; set; }
        public string birth { get; set; }
        public string adderss { get; set; }
        public string level { get; set; }
    }
}
